config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations"}
  resources :resets, only: [:new, :edit, :create, :update]

  resources :categories do
    resources :topics, shallow: true do
      resources :seasons do
        resources :episodes, shallow: true do
          member do
            get :video_modal
            post :comment
            delete :remove_comment
          end
          resources :quizes, shallow: true
        end
      end
    end

    member do
      get :message_board
    end

    resources :messages, shallow:true, only: [:index, :show, :new, :create, :destroy] do
    end

    collection do
      post :quiz_questions
    end
  end

  resources :users, only: [:update] do
    member do
      get :profile
      post :upload_image
    end
  end

  namespace :dashboard do
    get :index
    get :forum
    get :videos
    get :permission
    post :update_permission
    get :quizzes
    get :questions
    post :send_message
  end
  # resources :asset_libraries, only: [:index, :create, :delete]
  #
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  namespace :hr_manager, path: '' do
    resources :groups, except: [:edit, :update] do
      resources :group_employees, only: [:create, :destroy]
    end
    resources :quizzes, only: [:new , :create, :show, :destroy] do
      collection do
        get :assign_questions
        get :add_questions
      end
    end
    resources :questions, only: [:new , :create, :destroy]
    resources :asset_libraries, only: [:index] do
      collection do
        post :upload_file
        delete :destroy_file
      end
    end
    resources :assignments, only: [:index, :new, :create] do
      collection do
        get :select_content
      end
    end
  end

  namespace :employee, path: '' do
    resources :take_quiz, only: [] do
      collection do
        get 'take_a_quiz'
      end
    end
  end


  get "/home/contact" => "home#contact"
  get "/quizes", to: "quizes#index"
  get :select_box, to: "home#select_box"
  get :set_card_info, to: "home#set_card_info"

  get :contact, to: "home#contact"
  get :about_us, to: "home#about_us"
  get :disclaimer, to: "home#disclaimer"

  post "/home/hook" => "home#hook"
  root to: "categories#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_type, except: [:send_message]

  def index
  end

  def forum
  end

  def videos
  end

  def permission
  end

  def update_permission
    @category = Category.find(params[:category_id])
    @category_option = CategoryOption.find_or_create_by(category_id: @category.id)
    @category_option.update_attributes(user_id:current_user.id,message_board:params[:message_board],comment_section:params[:comment_section])
    render json: {status: "success"}
  end

  def quizzes
    @quizzes = current_user.quizzes
  end

  def questions
    @questions = current_user.questions
  end


  def send_message 
    @service = WatsonLayer::ApiCall.new
    @message = @service.send_message(params[:message])
    respond_to do |format|
      format.js
    end  
  end  

  private
  def check_user_type
    unless current_user.user_type == "hr_manager"
      flash[:notice] = "HR_Managers only can access dashboard page"
      redirect_to root_path
    else
      true
    end
  end
end

app/views/dashboard/_left_side_dashboard.html.haml
.side-header
  = link_to "Dashboard", "javascript://", class:"title-header"
  %span EDIT PREFERENCES
#accordion.panel-group
  #panel1.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a.collapsed{"data-target" => "#collapseOne", "data-toggle" => "collapse", :href => dashboard_permission_path, class: params[:action] == "permission" ? "" : "collapsed"}
          %strong PERMISSIONS
    #collapseOne.panel-collapse.collapse{class: params[:action] == "permission" ? "in" : ""}
      .panel-body Permissions
  #panel2.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseTwo", "data-toggle" => "collapse", :href => dashboard_videos_path, class: params[:action] == "videos" ? "" : "collapsed"}
          %strong VIDEOS
    #collapseTwo.panel-collapse.collapse{class: params[:action] == "videos" ? "in" : ""}
      .panel-body Blogs
  #panel3.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseThree", "data-toggle" => "collapse", :href => hr_manager_groups_path, class: (params[:controller] == "hr_manager/groups" && params[:action] == "index") ? "" : "collapsed"}
          %strong GROUPS
    #collapseThree.panel-collapse.collapse{class: params[:action] == "groups" ? "in" : ""}
      .panel-body Groups
  #panel4.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseFour", "data-toggle" => "collapse", :href => dashboard_forum_path, class: params[:action] == "forum" ? "" : "collapsed"}
          %strong FORUMS
    #collapseFour.panel-collapse.collapse{class: params[:action] == "forum" ? "in" : ""}
      .panel-body Forums
  #panel5.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a.collapsed{"data-target" => "#collapseFive", "data-toggle" => "collapse", :href => "#collapseFive"}
          %strong LANGUAGES
    #collapseFive.panel-collapse.collapse
      .panel-body Languages
  #panel6.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseSix", "data-toggle" => "collapse", :href => hr_manager_asset_libraries_path, class: params[:action]=="asset_libraries" ? "" : "collapsed"}
          %strong ASSETS LIBRARIES
    #collapseSix.panel-collapse.collapse{class: params[:action]=="asset_libraries" ? "in" : ""}
      .panel-body Assets Libraries
  #panel7.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseSeven", "data-toggle" => "collapse", :href => dashboard_quizzes_path, class: params[:action]=="quizzes" ? "" : "collapsed"}
          %strong QUIZZES
    #collapseSeven.panel-collapse.collapse{class: params[:action]=="quizzes" ? "in" : ""}
      .panel-body Quizzes
  #panel8.panel.panel-default
    .panel-heading
      %h4.panel-title
        %a{"data-target" => "#collapseEight", "data-toggle" => "collapse", :href => dashboard_questions_path, class: params[:action]=="quizzes" ? "" : "collapsed"}
          %strong QUESTIONS
    #collapseEight.panel-collapse.collapse{class: params[:action]=="quizzes" ? "in" : ""}
      .panel-body Questions

app/views/dashboard/asset_libraries.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.assets_libraries-content
      %h3{style:"text-align:center;padding-top:20px;"} Asset Libraries
      = form_tag dashboard_upload_file_path, multipart:true, class:"form-inline" do
        .row
          .col-md-12
            .form-group
              %label{:for => "category"} Category
              = select_tag :category, options_from_collection_for_select(Category.all, "id", "title", 1), class: "form-control"
            .form-group
              .input-group
                %label.input-group-btn
                  %span.btn.btn-primary
                    Browse…
                    %input{:multiple => "multiple", :style => "display: none;", :type => "file", name:"file", required: true}/
                %input.form-control{:readonly => "readonly", :type => "text"}/
            = submit_tag "Upload", class: "btn btn-primary"
    .row.assets_libraries-content
      .col-sm-12{style:"margin-bottom:60px;"}
        %table.table.table-responsive.table-striped.table-bordered
          %thead
            %tr
              %th File Name
              %th Category
              %th.hidden-xs Uploaded At
              %th Manage
          %tbody
            - @asset_libraries.each do |asset|
              %tr
                %td= link_to File.basename(asset.file.path), asset.file.url, target: "_blank"
                %td
                  %span.hidden-xs
                    = link_to asset.category.title, category_path(asset.category) if asset.category.present?
                  %span.visible-xs
                    = link_to asset.category.id, category_path(asset.category) if asset.category.present?
                %td.hidden-xs= asset.created_at.strftime("%b %dth %Y")
                %td{style:"text-align:center;"}
                  = link_to dashboard_destroy_file_path(id:asset.id), method: :delete, data:{confirm: "Are you sure"} do
                    %span.glyphicon.glyphicon-trash{"aria-hidden" => "true"}
        = paginate @asset_libraries
        -# = will_paginate @asset_libraries, renderer: BootstrapPagination::Rails
:javascript
  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });

app/views/dashboard/forum.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.forum-content
      .col-sm-12
        %h1.forum-title Message Boards
      - Category.all.each do |cat|
        .col-sm-8.forum-item
          = link_to message_board_category_path(cat) do
            %h3= cat.title
        .col-sm-4.forum-item
          %label
            = cat.messages.count
            comments

app/views/dashboard/groups.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9.groups-page
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.page-content
      .col-sm-12
        %h1.page-title Groups
        = link_to 'Add Assignment', new_assignment_path, class: "pull-right btn btn-info"
        = link_to 'Create Group', new_hr_manager_group_path, class: 'btn btn-info pull-right'
    .clearfix
    .row.groups
      .col-sm-12{style:"margin-top:25px;"}
        %table.table.table-responsive.table-striped.table-bordered
          %thead
            %tr
              %th Name
              %th HR Manager
              %th Employees Count
              %th Actions
          %tbody
            - @groups.each do |group|
              %tr
                %td.employee_groups{"data-link" => "#{hr_manager_group_path(group)}"}= group.name
                %td.employee_groups{"data-link" => "#{hr_manager_group_path(group)}"}= group.hr_manager.email
                %td.employee_groups{"data-link" => "#{hr_manager_group_path(group)}"}= group.group_employees.count
                %td
                  = link_to hr_manager_group_path(group), method: :delete, class: "btn btn-danger btn-sm employee_groups_remove_link", data: { confirm: "Are you sure you want to delete it?" } do
                    %span.glyphicon.glyphicon-trash
        = paginate @groups

app/views/dashboard/index.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row

app/views/dashboard/permission.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.permission-content
      .col-sm-12{style:"margin-top:30px;margin-bottom:20px;"}
        %h1.forum-title Permission
      - Category.all.each do |cat|
        - category_option = cat.category_option(current_user)
        .row{style:"margin-top:20px;margin-left:3px;"}
          .col-sm-4.permission-item.category-title-item
            = link_to message_board_category_path(cat) do
              %h4= cat.title
          .col-sm-8.permission-item
            .row
              .col-sm-6
                %label Message Board
              .col-sm-6
                %label.switch
                  - if category_option.present?
                    %input.message-board{:type => "checkbox",name:"message_board", data:{category:cat.id}, class:"mesage-board-#{cat.id}", checked: category_option.message_board}/
                  - else
                    %input.message-board{:type => "checkbox",name:"message_board", data:{category:cat.id}, class:"mesage-board-#{cat.id}"}/
                  .slider.round
            .row
              .col-sm-6
                %label Comment Section
              .col-sm-6
                %label.switch
                  - if category_option.present?
                    %input.comment-section{:type => "checkbox",name:"comment_section", data:{category:cat.id}, class: "comment-section-#{cat.id}", checked: category_option.comment_section}/
                  - else
                    %input.comment-section{:type => "checkbox",name:"comment_section", data:{category:cat.id}, class: "comment-section-#{cat.id}"}/
                  .slider.round


:javascript
  $(".switch input").change(function(){
    var cat_id = $(this).data("category");
    var action_url = "/dashboard/update_permission"
    var message_board_status = $(".mesage-board-"+cat_id).prop('checked');
    var comment_section_status = $(".comment-section-"+cat_id).prop('checked');
    $.post(action_url, {category_id:cat_id, message_board: message_board_status, comment_section: comment_section_status}, function(data){
      console.log(data);
    })
  });

  $(".comment-section").change(function(){

  });

app/views/dashboard/questions.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9.groups-page
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.page-content
      .col-sm-12.mar-top-20
        %h1.page-title Question
        = link_to 'Add Question', new_hr_manager_question_path, class: "pull-right btn btn-info"
    .clearfix
    .row.groups
      .col-sm-12{style:"margin-top:25px;"}
        %table.table.table-responsive.table-striped.table-bordered
          %thead
            %tr
              %th No.
              %th Question
              %th Actions
          %tbody
            - @questions.each_with_index do |question, i|
              %tr
                %td
                  = (i+1)
                %td
                  = question.question_text
                  .cealerfix
                  %table.table
                    %thead
                      %tr
                        %th Option Name
                        %th value
                        %th is Answer
                    - question.question_options.each do |q_o|
                      %tr
                        %td
                          = q_o.option_name
                        %td
                          = q_o.value
                        %td
                          =q_o.is_answer
                %td
                  = link_to hr_manager_question_path(question), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete it?" } do
                    %span.glyphicon.glyphicon-trash
               
          

app/views/dashboard/quizzes.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9.groups-page
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.page-content
      .col-sm-12.mar-top-20
        %h1.page-title Quizzes
        = link_to 'Add Quiz', new_hr_manager_quiz_path, class: "pull-right btn btn-info"
    .clearfix
    .row.groups
      .col-sm-12{style:"margin-top:25px;"}
        %table.table.table-responsive.table-striped.table-bordered
          %thead
            %tr
              %th Name
              %th Actions
          %tbody
            - @quizzes.each do |quiz|
              %tr
                %td
                  = link_to quiz.name , hr_manager_quiz_path(quiz)
                %td
                  = link_to hr_manager_quiz_path(quiz), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete it?" } do
                    %span.glyphicon.glyphicon-trash
               
          

app/views/dashboard/send_message.js.haml
setTimeout(function(){
$('.msg_container_base').append("#{escape_javascript(render 'shared/message',:@message => @message)}");
}, 1000);

app/views/dashboard/videos.html.haml
.dashboard-page
  .col-sm-3.side_nav
    = render "left_side_dashboard"
  .col-sm-9
    .row
      .col-sm-12.content-header
        %label alerts - messages - ad space
    .row.episode-content      
      -Episode.all.each do |episode|
        .col-md-4.col-sm-6.episode-item
          = link_to episode_path(episode), class: "thumbnail" do
            = image_tag(episode.snap_shot.url) if episode.snap_shot.url
            %label.episode-title= episode.title