config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations"}
  resources :resets, only: [:new, :edit, :create, :update]

  resources :categories do
    resources :topics, shallow: true do
      resources :seasons do
        resources :episodes, shallow: true do
          member do
            get :video_modal
            post :comment
            delete :remove_comment
          end
          resources :quizes, shallow: true
        end
      end
    end

    member do
      get :message_board
    end

    resources :messages, shallow:true, only: [:index, :show, :new, :create, :destroy] do
    end

    collection do
      post :quiz_questions
    end
  end

  resources :users, only: [:update] do
    member do
      get :profile
      post :upload_image
    end
  end

  namespace :dashboard do
    get :index
    get :forum
    get :videos
    get :permission
    post :update_permission
    get :quizzes
    get :questions
    post :send_message
  end
  # resources :asset_libraries, only: [:index, :create, :delete]
  #
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  namespace :hr_manager, path: '' do
    resources :groups, except: [:edit, :update] do
      resources :group_employees, only: [:create, :destroy]
    end
    resources :quizzes, only: [:new , :create, :show, :destroy] do
      collection do
        get :assign_questions
        get :add_questions
      end
    end
    resources :questions, only: [:new , :create, :destroy]
    resources :asset_libraries, only: [:index] do
      collection do
        post :upload_file
        delete :destroy_file
      end
    end
    resources :assignments, only: [:index, :new, :create] do
      collection do
        get :select_content
      end
    end
  end

  namespace :employee, path: '' do
    resources :take_quiz, only: [] do
      collection do
        get 'take_a_quiz'
      end
    end
  end


  get "/home/contact" => "home#contact"
  get "/quizes", to: "quizes#index"
  get :select_box, to: "home#select_box"
  get :set_card_info, to: "home#set_card_info"

  get :contact, to: "home#contact"
  get :about_us, to: "home#about_us"
  get :disclaimer, to: "home#disclaimer"

  post "/home/hook" => "home#hook"
  root to: "categories#index"
end

app/views/shared/_chat.html.haml
#chat_window_1.row.chat-window.col-xs-5.col-md-3{:style => "margin-left:10px;"}
  .col-xs-12.col-md-12
    .panel.panel-default
      .panel-heading.top-bar
        .col-md-6.col-xs-6
          %h3.panel-title
            %span.glyphicon.glyphicon-comment
            Chat
        .col-md-6.col-xs-6{:style => "text-align: right;"}
          %a{:href => "#"}
            %span#minim_chat_window.glyphicon.glyphicon-minus.icon_minim
          %a{:href => "#"}
            %span.glyphicon.glyphicon-remove.icon_close{"data-id" => "chat_window_1"}
      .panel-body.msg_container_base
        .row.msg_container.base_sent#sent
          .col-md-2.col-xs-2.avatar
            %img.img-responsive{:src => "http://www.bitrebels.com/wp-content/uploads/2011/02/Original-Facebook-Geek-Profile-Avatar-1.jpg"}/
          .col-md-10.col-xs-10
            .messages.msg_sent#sent
              %p.msg_p
                Hi, How can I help you?
              %time{:datetime => DateTime.now} Default • 51 min
          
        
      .panel-footer
        .input-group
          %input#btn-input.form-control.input-sm.chat_input{:placeholder => "Write your message here...", :type => "text"}/
          %span.input-group-btn
            %button#btn-chat.btn.btn-primary.btn-sm Send
.btn-group.dropup
  %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
    %span.glyphicon.glyphicon-cog
    %span.sr-only Toggle Dropdown
  %ul.dropdown-menu{:role => "menu"}
    %li
      %a#new_chat{:href => "#"}
        %span.glyphicon.glyphicon-plus
        Novo
    %li
      %a{:href => "#"}
        %span.glyphicon.glyphicon-list
        Ver outras
    %li
      %a{:href => "#"}
        %span.glyphicon.glyphicon-remove
        Fechar Tudo
    %li.divider
    %li
      %a{:href => "#"}
        %span.glyphicon.glyphicon-eye-close
        Invisivel

app/views/shared/_dashboard_menu.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand', style:"padding:0px" do
        = image_tag "BoxSpringLogo.jpg", height: "100%;"
    #navbar1.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"} MT PROFILE
        %li
          %a{:href => "#"} EDIT
        %li
          %a{:href => "#"} VIEW
        %li
          %a{:href => "#"} PREFERENCES
        %li
          %a{:href => "#"} PRIVACY
        %li
          = link_to "LOG-OUT", destroy_user_session_path, method: :delete, class: "item"
      .col-sm-3.col-md-3.pull-right
        %form.navbar-form{:role => "search"}
          .input-group
            %input.form-control{:name => "q", :placeholder => "Search", :type => "text"}/
            .input-group-btn
              %button.btn.btn-default{:type => "submit"}
                %i.glyphicon.glyphicon-search

app/views/shared/_footer.html.haml
%footer.footer
  .container
    .row
      .col-md-3.col-sm-2
      .col-md-6.col-sm-8.col-xs-12{style:"text-align:center"}
        = link_to "About Us", about_us_path
        %label{style:"padding-left:10px;padding-right:10px;"}= "|"
        = link_to "Contact", contact_path
        %label{style:"padding-left:10px;padding-right:10px;"}= "|"
        = link_to "Disclaimer", disclaimer_path
    .row
      .col-md-12.hidden-xs{style:"text-align:center"}
        %small Boxspring Channel & H2H Corporation LLC  All Rights Reserved © 2017

app/views/shared/_menu.html.haml
#topMenu.pusher
  .full.height
    .following.bar
      .ui.large.secondary.network.menu
        #browse.view-ui.item.fitted
          .ui.simple.dropdown.item
            %i.sidebar.icon
            Browse
            .menu{style:"margin-top:0px;"}
              - Category.all.each do |category|
                = link_to category.title, category_path(category), class: "item"

        #logo.item.fitted
          .ui.logo.shape
            .sides
              .active.ui.side
                = link_to root_path do
                  = image_tag "BoxSpringLogo.jpg", class: "img-responsive", width:100, height:100
        #rightMenu.right.menu
          .ui.simple.dropdown.item
            %i.user.icon
            %span{style:"margin-right:5px;"}= current_user.first_name
            %span.hidden-xs= current_user.last_name
            %i.dropdown.icon
            .menu{style:"margin-top:0px;"}
              = link_to "Dashboard", dashboard_index_path, class: "item" if current_user.user_type == "hr_manager"
              = link_to "Profile", profile_user_path(current_user), class: "item"
              = link_to "Assignments", hr_manager_assignments_path, class: "item" if current_user.user_type == "hr_manager"
              = link_to "About Us", about_us_path, class: "item"
              = link_to "Logout", destroy_user_session_path, method: :delete, class: "item"

app/views/shared/_message.html.haml
.row.msg_container.base_sent#sent
  .col-md-2.col-xs-2.avatar
    %img.img-responsive{:src => "http://www.bitrebels.com/wp-content/uploads/2011/02/Original-Facebook-Geek-Profile-Avatar-1.jpg"}/
  .col-md-10.col-xs-10
    .messages.msg_sent#sent
      %p.msg_p
        =@message
      %time{:datetime => DateTime.now} Default • 51 min
  