config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: "sessions",registrations: "registrations"}
  resources :resets, only: [:new, :edit, :create, :update]

  resources :categories do
    resources :topics, shallow: true do
      resources :seasons do
        resources :episodes, shallow: true do
          member do
            get :video_modal
            post :comment
            delete :remove_comment
          end
          resources :quizes, shallow: true
        end
      end
    end

    member do
      get :message_board
    end

    resources :messages, shallow:true, only: [:index, :show, :new, :create, :destroy] do
    end

    collection do
      post :quiz_questions
    end
  end

  resources :users, only: [:update] do
    member do
      get :profile
      post :upload_image
    end
  end

  namespace :dashboard do
    get :index
    get :forum
    get :videos
    get :permission
    post :update_permission
    get :quizzes
    get :questions
    post :send_message
  end
  # resources :asset_libraries, only: [:index, :create, :delete]
  #
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  namespace :hr_manager, path: '' do
    resources :groups, except: [:edit, :update] do
      resources :group_employees, only: [:create, :destroy]
    end
    resources :quizzes, only: [:new , :create, :show, :destroy] do
      collection do
        get :assign_questions
        get :add_questions
      end
    end
    resources :questions, only: [:new , :create, :destroy]
    resources :asset_libraries, only: [:index] do
      collection do
        post :upload_file
        delete :destroy_file
      end
    end
    resources :assignments, only: [:index, :new, :create] do
      collection do
        get :select_content
      end
    end
  end

  namespace :employee, path: '' do
    resources :take_quiz, only: [] do
      collection do
        get 'take_a_quiz'
      end
    end
  end


  get "/home/contact" => "home#contact"
  get "/quizes", to: "quizes#index"
  get :select_box, to: "home#select_box"
  get :set_card_info, to: "home#set_card_info"

  get :contact, to: "home#contact"
  get :about_us, to: "home#about_us"
  get :disclaimer, to: "home#disclaimer"

  post "/home/hook" => "home#hook"
  root to: "categories#index"
end

app/models/category.rb
# === Schema Information
#
# Table name: categories
#
# id              :integer not null, primary key
# category_id     :integer
# title           :string
# description     :text
# icon            :string
# banner          :string
# snap_shot       :string
#
# created_at      :datetime
# updated_at      :datetime
class Category < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :seasons, dependent: :destroy
  has_many :episodes, dependent: :destroy
  has_many :messages, as: :messageable
  has_many :asset_libraries
  has_many :category_options
  has_many :assignments, as: :content, dependent: :destroy
  has_many :quizzes, as: :content, dependent: :destroy
  has_many :questions, dependent: :destroy

  mount_uploader :snap_shot, SnapShotUploader
  mount_uploader :banner, BannerUploader

  scope :most_recent, -> (limit) { order("created_at desc").limit(limit) }
  def category_option user
    category_options.find_by(user_id:user.id)
  end

  def message_board_permission user
    return true if user.single_user?
    user = user.hr_manager unless user.hr_manager?
    cat_option = category_options.find_by(user_id:user.id)
    cat_option.present? and cat_option.message_board == true
  end

  def comment_section_permission user
    return true if user.single_user?
    user = user.hr_manager unless user.hr_manager?
    cat_option = category_options.find_by(user_id:user.id)
    cat_option.present? and cat_option.comment_section == true
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @employee_assignments = Assignment.employee_assignments
    @categories = Category.order('category_id').all
    @user = User.find_by_id(session[:user_id])
  end

  def show
    @user = User.find_by_id(session[:user_id])
    @categories = Category.order('category_id').all
    @category =  params[:category_id].present? ? Category.find(params[:category_id]) : Category.find(params[:id])
    @season = Season.where(category_id: @category.id).first
    @episodes = Episode.all
  end

  def message_board
    @category = Category.find(params[:id])
    @messages = @category.messages
  end

  def quiz_questions
    @quiz = Quiz.find(params[:quiz_questoins][:quiz_id]) rescue nil
    @quiz_questions = current_user.questions - @quiz.quiz_questions.map(&:question)

    question_ids = params[:quiz_questoins][:question_id].map(&:last)
    question_ids.delete("0")
    question_ids.each do |question_id|
      quiz_question = @quiz.quiz_questions.new(question_id: question_id) 
      quiz_question.save
    end
    flash[:notice] = "Question assigned sucesfully."
    redirect_to :back
  end
end

app/views/categories/_modals.html.haml
#tool1.ui.basic.modal
  %i.close.icon
  .header
    Introduction To The SOCME Academy:
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/366043", :webkitallowfullscreen => "", :width => "854"}
#tool2.ui.basic.modal
  %i.close.icon
  .header
    How To Use LinkedIn Effectively:
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/366041", :webkitallowfullscreen => "", :width => "854"}
#tool3.ui.basic.modal
  %i.close.icon
  .header
    Low CQ:
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/365338", :webkitallowfullscreen => "", :width => "854"}
#tool4.ui.basic.modal
  %i.close.icon
  .header
    High CQ:
  %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/365337", :webkitallowfullscreen => "", :width => "854"}

app/views/categories/index.html.haml
#content.uui.category-index
  .grid.rows
    .category-slick
      - @categories.each do |category|
        %div
          = link_to category_path(category) do
            %h1.formatHeader= category.title
          = link_to category_path(category) do
            .banner
              = image_tag category.banner.url if category.banner.present?

.col-md-6.mar-top-20
  %h3 Assigned to employees
  %table.table
    %head
      %tr
        %th HR Manager Name
        %th Assignee
    - @employee_assignments.each do |employee_assignment|
      %tbody
        -if current_user.user_type == "employee" && employee_assignment.assignee == current_user
          %tr 
            %td= employee_assignment.assignee.hr_manager.full_name
            -if employee_assignment.content_type == "Category"
              %td 
                =link_to "#{employee_assignment.content.title} ( #{employee_assignment.content_type})",  category_path(employee_assignment.content)
            -elsif employee_assignment.content_type == "Topic"
              %td 
                =link_to "#{employee_assignment.content.title} ( #{employee_assignment.content_type})",  topic_path(employee_assignment.content)
            -elsif employee_assignment.content_type == "Season"
              %td 
                =link_to "#{employee_assignment.content.title} ( #{employee_assignment.content_type})",  season_path(employee_assignment.content)
            -elsif employee_assignment.content_type == "Episode"
              %td 
                =link_to "#{employee_assignment.content.title} ( #{employee_assignment.content_type})",  episode_path(employee_assignment.content)

        

app/views/categories/message_board.html.haml
- if @category.message_board_permission current_user
  .container.message-board-page
    .row
      .col-sm-12
        %h1
          TOPIC:
          = @category.title
      .col-sm-12
        = form_tag category_messages_path(@category) do
          .form-group
            %label.control-label{:for => "message-text"} Message:
            %textarea#summernote.form-control{name:"body"}
          .form-group
            = submit_tag "Post Message", class:"btn btn-primary"
    .row{style:"margin-bottom:50px;"}
      - @messages.each do |message|
        .row.message-list
          .col-sm-1.col-xs-2
            .thumbnail
              - if current_user.avatar.present?
                = image_tag message.user.avatar.url, class:"img-responsive user-photo"
              - else
                = image_tag "avatar.png", class:"img-responsive user-photo"
          .col-sm-10.col-xs-8
            .panel.panel-default
              .panel-heading
                %strong= message.user.full_name
                %span.text-muted
                  sent
                  = message.messaged_time_string
                = link_to "Remove", message_path(message, category_id:@category.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm pull-right", style:"margin-top:-5px;" if message.user.id == current_user.id
              .panel-body
                = raw message.body
  / Modal
  #post_message.modal.fade{"aria-labelledby" => "post_message_label", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document", style:"margin-top: 100px;"}
      .modal-content
        .modal-header
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h4#post_message_label.modal-title New message
        .modal-body
          = form_tag category_messages_path(@category) do
            .form-group
              %label.control-label{:for => "message-text"} Message:
              %textarea.summernote.form-control
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          %button.btn.btn-primary{:type => "button"} Send message

:javascript
  $(document).ready(function() {
    $('#summernote').summernote({
      height: 100
    });
  });

app/views/categories/old_show.html.haml
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"
.banner
  %div
#content
  = link_to category_path(@category) do
    %h1#formatHeaderShow= @category.title
  .seasonShow
    %div
      = image_tag @category.snap_shot.url, class: "img-responsive", height: 800, width:"100%" if @category.snap_shot.present?
      #previewNow
        %button#preview.ui.red.small.button.disabled
          Coming Soon
      #episodeRow
        - @episodes.each do |episode|
          - if episode.series_id == @season.series_id
            -# = link_to video_modal_episode_path(episode), remote: true, class: "episode-video-modal-link" do
            = link_to episode_path(episode), class: "episode-show-link" do
              .square
                = image_tag episode.snap_shot.url, class:"img-responsive", height:145, width: "100%" if episode.snap_shot.present?
                .belowText
                  .episode
                  .episode-title
                    = episode.title
#topicShow
#tools
  %h1#toolsHeader TOOLS
  %p Thoughfully curated, the following audio books, podcasts, games, VR short films, and immersive content pieces ought to provide any type of learner an engaging way to learn more about this subject.
  - if @category.category_id.to_i == 3
    = image_tag "SocMePic.jpg", :class => 'SocMe'
    = image_tag "LinkedInPic.jpg", :class => 'LinkedIn'
  - elsif @category.category_id.to_i != 3
#convo
  - if @category.category_option.present? and @category.category_option.message_board
    = link_to message_board_category_path(@category) do
      %h1 Join The Conversation
  - else
    %h1 Join The Conversation
  %p Many of us enjoy discussion what we are learning with others, so we've created a safe are for engagement. Please talk to your manager if this area requires "unlocking". In addition, on your own person platforms you can use the # tag from the list provided and automatically join groups on twitter and other platforms that are hosting these discussions.

#clicky.ui.basic.modal
  %i.close.icon
  .header
    - if @category.category_id == 1
      The HR Files
      %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/365340", :webkitallowfullscreen => "", :width => "854"}
    - elsif @category.category_id == 3
      Hacks
    - elsif @category.category_id == 4
      Sea Knot
    - elsif @category.category_id == 2
      Communication

#episode_video.ui.basic.modal
=render "modals"

app/views/categories/quiz_questions.html.haml
#quiz_questions.mar-top-20
  .col-md-12
    %h1 #{ @quiz.name } Questions
    %table.table
      %thead
        %tr
          %th Question
          %th Options
      %tbody
        - @quiz_questions.each do |question|
          %tr
            %td 
              = question.question_text
            %td
              %table.table
                %thead
                  %tr
                    %th Option Name
                    %th value
                    %th is Answer
                - question.question_options.each do |q_o|
                  %tr
                    %td= q_o.option_name
                    %td= q_o.value
                    %td=q_o.is_answer

app/views/categories/show.html.haml
= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"
.category-show-page
  .row
    .col-md-12
      = link_to category_path(@category) do
        %h1#formatHeaderShow= @category.title
  .row
    .col-md-12{style:"padding:0px;"}
      = image_tag @category.snap_shot.url, class: "img-responsive", height: 800, width:"100%" if @category.snap_shot.present?
    .col-md-10.col-md-offset-1{style:"margin-top:-13%"}
      .row.episode-slick{style:"margin-left: -15px; margin-right: -15px;"}
        - @episodes.each do |episode|
          - if episode.present? && @season.present? && (episode.series_id == @season.series_id)
            .col-md-3.col-sm-3.col-xs-3
              = link_to episode_path(episode), class: "episode-show-link" do
                .episode-image
                  = image_tag episode.snap_shot.url, class:"img-responsive", height:145, width: "100%" if episode.snap_shot.present?
                .episode-title.hidden-xs
                  = episode.title
                .episode-title.episode-title-small.visible-xs
                  %small= episode.title
    -# .col-md-10.col-md-offset-1.visible-md.visible-lg{style:"position: relative;margin-top: -18%;"}
    -#   %button#preview.ui.red.small.button.disabled
    -#     Coming Soon
  .row
    #tools
      %h1#toolsHeader TOOLS
      %p
        Thoughfully curated, the following audio books, podcasts, games, VR short films,
        and immersive content pieces ought to provide any type of learner an engaging way to learn more about this subject.
      - if @category.category_id.to_i == 3
        = image_tag "SocMePic.jpg", :class => 'SocMe'
        = image_tag "LinkedInPic.jpg", :class => 'LinkedIn'
      - elsif @category.category_id.to_i != 3


    #quizzes.mar-top-20
      .col-md-12
        %h1.text-center Quizzes
        .quizzes
          - @category.quizzes.each do |quiz|
            .col-md-2
              = link_to quiz.name, take_a_quiz_employee_take_quiz_index_path(quiz_id: quiz.id)
    .clearfix

    #convo
      - if @category.message_board_permission current_user
        = link_to message_board_category_path(@category) do
          %h1 Join The Conversation
      - else
        %h1 Join The Conversation
      %p
        Many of us enjoy discussion what we are learning with others, so we've created a safe are for engagement.
        Please talk to your manager if this area requires "unlocking". In addition, on your own person platforms
        you can use the # tag from the list provided and automatically join groups on twitter and other platforms
        that are hosting these discussions.

    #clicky.ui.basic.modal
      %i.close.icon
      .header
        - if @category.category_id == 1
          The HR Files
          %iframe{:allowfullscreen => "", :frameborder => "0", :height => "480", :mozallowfullscreen => "", :msallowfullscreen => "", :oallowfullscreen => "", :scrolling => "no", :src => "//iframe.dacast.com/b/83869/f/365340", :webkitallowfullscreen => "", :width => "854"}
        - elsif @category.category_id == 3
          Hacks
        - elsif @category.category_id == 4
          Sea Knot
        - elsif @category.category_id == 2
          Communication

  .row{style:"padding-bottom:50px;"}
#episode_video.ui.basic.modal
=render "modals"